FROM node:20

WORKDIR /app

# 必要なビルドツールを追加
RUN apt-get update && apt-get install -y \
    python3 make g++ \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json* ./
RUN echo ">>> INSTALLING DEPENDENCIES" && npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
